name: New Student Onboarding
on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: '0 10 * * *'
jobs:
  update-cesp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install
      - name: Onboard new students
        run: node pl-scripts/onboard.js
        env:
          GOOGLE_GROUPS_CLIENT_EMAIL: ${{ secrets.GOOGLE_GROUPS_CLIENT_EMAIL }}
          GOOGLE_GROUPS_PRIVATE_KEY: ${{ secrets.GOOGLE_GROUPS_PRIVATE_KEY }}
          GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL }}
          GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }}
          GMAIL_CLIENT_EMAIL: ${{ secrets.GMAIL_CLIENT_EMAIL }}
          GMAIL_PRIVATE_KEY: ${{ secrets.GMAIL_PRIVATE_KEY }}
          SFDC_LOGIN_URL: ${{ secrets.SFDC_LOGIN_URL }}
          SFDC_USERNAME: ${{ secrets.SFDC_USERNAME }}
          SFDC_PASSWORD: ${{ secrets.SFDC_PASSWORD }}
          GIT_AUTH_TOKEN: ${{ secrets.GIT_AUTH_TOKEN }}
          LEARN_TOKEN: ${{ secrets.LEARN_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
