name: repo-completion
on:
  workflow_dispatch:
    inputs:
      cohort:
        description: 'Cohort ID'
        required: false
        default: 'seip2201'
      tech_mentors:
        description: 'Optional: Tech mentor first names (space-separated)'
        required: false
      projects:
        description: 'Optional: Project names (space-separated)'
        required: false
  schedule:
    - cron: '0 13,16,19,22 * * *'
jobs:
  repo-completion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-v2
      - name: Install dependencies
        run: yarn install
      - name: Run repo completion
        run: xvfb-run --auto-servernum node pl-scripts/completion/cli.js --cohort ${{ github.event.inputs.cohort }} --tech-mentors ${{ github.event.inputs.tech_mentors }} --projects ${{ github.event.inputs.projects }}
        env:
          GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }}
          GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL }}
          GITHUB_AUTH_USER: ${{ secrets.GIT_AUTH_USER }}
          GITHUB_AUTH_TOKEN: ${{ secrets.GIT_AUTH_TOKEN }}
          