name: update-cesp
on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: '0 10 * * *'
jobs:
  update-cesp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: yarn install
      - name: Update CES&P
        run: node pl-scripts/updateCESP.js
        env:
          GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.GOOGLE_SHEETS_CLIENT_EMAIL }}
          GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.GOOGLE_SHEETS_PRIVATE_KEY }}
